# Generated by Django 6.0.3 on 2026-03-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authority_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
