# Generated by Django 6.0.3 on 2026-03-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
