# Generated by Django 6.0.3 on 2026-03-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='citizen_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_officer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_proof',
            field=models.TextField(blank=True, null=True),
        ),
    ]
