# Generated by Django 6.0.3 on 2026-03-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0004_complaint_citizen_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='citizen_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
