# Generated by Django 6.0.3 on 2026-03-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0005_complaint_citizen_email_complaint_citizen_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='citizen_email',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='citizen_phone',
        ),
    ]
