# Generated by Django 6.0.3 on 2026-03-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0006_remove_complaint_citizen_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image_proof',
            field=models.TextField(blank=True, null=True),
        ),
    ]
