# Generated by Django 6.0.3 on 2026-03-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0007_complaint_image_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='escalating_officer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
